backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "img"
collections:
  - name: "recipes"
    label: "recipes"
    folder: "content/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "First Name", name: "first", widget: "string"}
      - {label: "Last Name", name: "last", widget: "string"}
      - {label: "Recipe Name", name: "recipe", widget: "string"}
      - {label: "Story", name: "description", widget: "text"}
      - {label: "Recipe", name: "body", widget: "markdown"}